In [1]:
import pandas as pd
import numpy as np


np.random.seed(42)

data = {
    "Student_ID": range(1, 101),
    "Study_Hours": np.random.normal(5, 2, 100),
    "Attendance": np.random.normal(75, 15, 100),
    "Marks": np.random.normal(65, 20, 100),
    "Gender": np.random.choice(["Male", "Female"], 100),
    "Department": np.random.choice(["CS", "IT", "EXTC"], 100)
}

df = pd.DataFrame(data)


df.loc[5, 'Marks'] = np.nan
df.loc[10, 'Attendance'] = np.nan
df.loc[20, 'Gender'] = None

df.head()

   Student_ID  Study_Hours  Attendance      Marks  Gender Department
0           1     5.993428   53.769439  72.155747    Male         IT
1           2     4.723471   68.690320  76.215691  Female         CS
2           3     6.295377   69.859282  86.661025  Female         IT
3           4     8.046060   62.965841  86.076041    Male       EXTC
4           5     4.531693   72.580714  37.446613    Male         IT

In [4]:
df.isnull().sum()

Student_ID     0
Study_Hours    0
Attendance     1
Marks          1
Gender         1
Department     0
dtype: int64

In [6]:
df['Marks'] = df['Marks'].fillna(df['Marks'].mean())
df['Attendance'] = df['Attendance'].fillna(df['Attendance'].mean())
df['Gender'] = df['Gender'].fillna(df['Gender'].mode()[0])

In [8]:
df['Study_Hours'] = df['Study_Hours'].clip(lower=0)
df['Attendance'] = df['Attendance'].clip(0, 100)
df['Marks'] = df['Marks'].clip(0, 100)

In [3]:
Q1 = df['Marks'].quantile(0.25)
Q3 = df['Marks'].quantile(0.75)
IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

outliers = df[(df['Marks'] < lower) | (df['Marks'] > upper)]
print(outliers)

    Student_ID  Study_Hours  Attendance       Marks Gender Department
9           10      6.08512   73.883311  142.054630   Male         IT
62          63      2.78733   92.378934    0.174653   Male         CS

In [5]:
df['Marks'] = np.where(df['Marks'] > upper, upper, df['Marks'])
df['Marks'] = np.where(df['Marks'] < lower, lower, df['Marks'])

In [7]:
df['Marks'].skew()

0.018348953652781514

In [9]:
df['Marks_log'] = np.log1p(df['Marks'])

In [11]:
df['Marks_scaled'] = (df['Marks'] - df['Marks'].mean()) / df['Marks'].std()

In [13]:
df.head()

,Student_ID,Study_Hours,Attendance,Marks,Gender,Department,Marks_log,Marks_scaled
0,1,5.993428,53.769439,72.155747,Male,IT,4.292591,0.278148
1,2,4.723471,68.690320,76.215691,Female,CS,4.346603,0.474044
2,3,6.295377,69.859282,86.661025,Female,IT,4.473477,0.978040
3,4,8.046060,62.965841,86.076041,Male,EXTC,4.466782,0.949814
4,5,4.531693,72.580714,37.446613,Male,IT,3.649271,-1.396600